mysql:
  build: .
  hostname: mysql
  dockerfile: Dockerfile-alt
  environment:
    - DB_USER=user
    - DB_USER_PASSWORD=password
    - ROOT_PASSWORD=password
  ports:
    - "3306:3306"
  volumes:
    - ./assets/post_inst.sh:/tmp/post_inst.sh
