FROM debian:jessie

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server-5.5 && \
  rm -rf /var/lib/apt/lists/* && \
  sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf

ENV DEBIAN_FRONTEND=newt

COPY assets/create_import_db.sh /tmp/create_import_db.sh
RUN chmod +x /tmp/create_import_db.sh

CMD ["mysqld"]

EXPOSE 3306
