version: '2'
services:
  mysql:
    build: .
    image: jonbrouse/mysql:downstream
    container_name: mysql
    hostname: mysql
    environment:
      - DB_USER=user
      - DB_USER_PASSWORD=password
      - ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - "./assets/:/tmp/"
