version: '2'
services:
  mysql:
    build: .
    container_name: mysql
    hostname: mysql
    command: --user=root
    environment:
      - DB_USER=user
      - DB_USER_PASSWORD=password
      - ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    #volumes:
    #  - "./assets/:/tmp/"
